# Generated by Django 5.0.14 on 2026-05-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_expected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('non_paye', 'Non Payé'), ('en_retard', 'En retard')], default='non_paye', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='core.club')),
                ('mandat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='core.mandat')),
            ],
            options={
                'verbose_name': 'Taxe Club',
                'verbose_name_plural': 'Taxes Clubs',
                'unique_together': {('club', 'mandat')},
            },
        ),
    ]
