# Generated by Django 6.0.5 on 2026-05-09 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donation_eventactivity_eventpack_post_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrd_word', models.TextField(blank=True, verbose_name='Mot du RRD')),
                ('rrd_photo', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Photo du RRD')),
                ('governor_word', models.TextField(blank=True, verbose_name='Mot du Gouverneur')),
                ('governor_photo', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Photo du Gouverneur')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Bannière Pays')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Contenu Page d'Accueil",
                'verbose_name_plural': "Contenu Page d'Accueil",
            },
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la journée')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.event')),
            ],
            options={
                'verbose_name': 'Jour du Programme',
                'verbose_name_plural': 'Jours du Programme',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la session')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('speakers', models.CharField(blank=True, max_length=200, verbose_name='Intervenants')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.eventday')),
            ],
            options={
                'verbose_name': 'Session du Programme',
                'verbose_name_plural': 'Sessions du Programme',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_notif', models.CharField(choices=[('info', 'Information'), ('payment', 'Paiement'), ('alert', 'Alerte')], default='info', max_length=50)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
