# Generated by Django 6.0.5 on 2026-05-09 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homepagecontent_eventday_eventsession_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_procuration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='core.eventpack'),
        ),
        migrations.AddField(
            model_name='participant',
            name='procuration_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscrits_par_procuration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_plan',
            field=models.CharField(choices=[('comptant', 'Comptant'), ('3x', 'En 3 fois')], default='comptant', max_length=20),
        ),
    ]
