# Generated by Django 6.0.5 on 2026-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_participant_is_procuration_participant_pack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_plan',
            field=models.CharField(choices=[('comptant', 'Comptant'), ('tontine', 'Par Tontine (Échelonné)')], default='comptant', max_length=20),
        ),
    ]
