# Generated by Django 6.0.5 on 2026-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_payment_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
