# Generated by Django 6.0.5 on 2026-05-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_participant_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
